name: Build (PR check)

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: test
      SQLITE: test.db
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24.x
          cache: npm

      - run: npm ci
      - run: npm run pretty
      - run: npm run test:cli
      - run: npm run lint
      - run: npm run build
      - run: npm run dbtypes:check
